name = "Sleek"
license = "MIT"
licenselink = "https://github.com/stewalec/hugo-sleek/blob/master/LICENSE.md"
description = "Sleek, minimal Hugo theme"
homepage = "https://codeberg.org/stewalec/hugo-sleek"
demosite = "https://alecstewart.com"
tags = ["hugo", "theme", "minimal"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Alec Stewart"
  homepage = "https://alecstewart.com"
