name = "Sleek"
license = "MIT"
licenselink = "https://codeberg.org/stewalec/hugo-sleek/src/branch/master/LICENSE.md"
description = "Sleek, minimal Hugo theme"
homepage = "https://codeberg.org/stewalec/hugo-sleek"
demosite = "https://alecstewart.com"
tags = ["theme", "minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Alec Stewart"
  homepage = "https://alecstewart.com"
